# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-31 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('kind', models.CharField(max_length=256)),
                ('is_led_active', models.BooleanField(default=False)),
                ('device_token', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PlantLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('brightness', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.Plant')),
            ],
        ),
    ]
