# Generated by Django 2.0.1 on 2018-06-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantlog',
            name='soil_water',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
