# Generated by Django 2.0.1 on 2018-06-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_plantlog_soil_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantlog',
            name='brightness',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='humidity',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='soil_water',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='temperature',
            field=models.CharField(max_length=256),
        ),
    ]
